// <auto-generated />
using System;
using MarketingScheduler.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240624082513_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MarketingScheduler.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CampainSendedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Deposit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNew")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 53,
                            City = "London",
                            Deposit = 104,
                            Gender = 0,
                            IsNew = false
                        },
                        new
                        {
                            Id = 2,
                            Age = 44,
                            City = "New York",
                            Deposit = 209,
                            Gender = 1,
                            IsNew = true
                        },
                        new
                        {
                            Id = 3,
                            Age = 36,
                            City = "New York",
                            Deposit = 208,
                            Gender = 0,
                            IsNew = true
                        },
                        new
                        {
                            Id = 4,
                            Age = 87,
                            City = "London",
                            Deposit = 134,
                            Gender = 1,
                            IsNew = false
                        },
                        new
                        {
                            Id = 5,
                            Age = 54,
                            City = "Paris",
                            Deposit = 123,
                            Gender = 0,
                            IsNew = true
                        },
                        new
                        {
                            Id = 6,
                            Age = 45,
                            City = "New York",
                            Deposit = 210,
                            Gender = 1,
                            IsNew = true
                        },
                        new
                        {
                            Id = 7,
                            Age = 49,
                            City = "Tel-Aviv",
                            Deposit = 174,
                            Gender = 1,
                            IsNew = false
                        },
                        new
                        {
                            Id = 8,
                            Age = 35,
                            City = "Paris",
                            Deposit = 52,
                            Gender = 0,
                            IsNew = true
                        },
                        new
                        {
                            Id = 9,
                            Age = 61,
                            City = "Tel-Aviv",
                            Deposit = 151,
                            Gender = 0,
                            IsNew = false
                        },
                        new
                        {
                            Id = 10,
                            Age = 78,
                            City = "Paris",
                            Deposit = 57,
                            Gender = 0,
                            IsNew = false
                        },
                        new
                        {
                            Id = 11,
                            Age = 41,
                            City = "New York",
                            Deposit = 131,
                            Gender = 1,
                            IsNew = false
                        },
                        new
                        {
                            Id = 12,
                            Age = 32,
                            City = "Tel-Aviv",
                            Deposit = 154,
                            Gender = 1,
                            IsNew = true
                        },
                        new
                        {
                            Id = 13,
                            Age = 62,
                            City = "Paris",
                            Deposit = 135,
                            Gender = 1,
                            IsNew = false
                        },
                        new
                        {
                            Id = 14,
                            Age = 67,
                            City = "Tel-Aviv",
                            Deposit = 153,
                            Gender = 0,
                            IsNew = true
                        },
                        new
                        {
                            Id = 15,
                            Age = 68,
                            City = "London",
                            Deposit = 241,
                            Gender = 1,
                            IsNew = true
                        },
                        new
                        {
                            Id = 16,
                            Age = 41,
                            City = "London",
                            Deposit = 134,
                            Gender = 0,
                            IsNew = false
                        },
                        new
                        {
                            Id = 17,
                            Age = 46,
                            City = "London",
                            Deposit = 212,
                            Gender = 1,
                            IsNew = false
                        },
                        new
                        {
                            Id = 18,
                            Age = 77,
                            City = "Tel-Aviv",
                            Deposit = 97,
                            Gender = 1,
                            IsNew = true
                        },
                        new
                        {
                            Id = 19,
                            Age = 51,
                            City = "London",
                            Deposit = 141,
                            Gender = 0,
                            IsNew = true
                        },
                        new
                        {
                            Id = 20,
                            Age = 80,
                            City = "Paris",
                            Deposit = 189,
                            Gender = 0,
                            IsNew = false
                        },
                        new
                        {
                            Id = 21,
                            Age = 31,
                            City = "Tel-Aviv",
                            Deposit = 134,
                            Gender = 1,
                            IsNew = true
                        },
                        new
                        {
                            Id = 22,
                            Age = 80,
                            City = "Tel-Aviv",
                            Deposit = 81,
                            Gender = 1,
                            IsNew = false
                        },
                        new
                        {
                            Id = 23,
                            Age = 36,
                            City = "London",
                            Deposit = 237,
                            Gender = 1,
                            IsNew = true
                        },
                        new
                        {
                            Id = 24,
                            Age = 65,
                            City = "Tel-Aviv",
                            Deposit = 119,
                            Gender = 1,
                            IsNew = false
                        },
                        new
                        {
                            Id = 25,
                            Age = 72,
                            City = "Tel-Aviv",
                            Deposit = 139,
                            Gender = 0,
                            IsNew = false
                        },
                        new
                        {
                            Id = 26,
                            Age = 64,
                            City = "Tel-Aviv",
                            Deposit = 128,
                            Gender = 0,
                            IsNew = true
                        },
                        new
                        {
                            Id = 27,
                            Age = 29,
                            City = "London",
                            Deposit = 76,
                            Gender = 0,
                            IsNew = true
                        },
                        new
                        {
                            Id = 28,
                            Age = 25,
                            City = "London",
                            Deposit = 203,
                            Gender = 0,
                            IsNew = true
                        },
                        new
                        {
                            Id = 29,
                            Age = 77,
                            City = "New York",
                            Deposit = 54,
                            Gender = 0,
                            IsNew = true
                        },
                        new
                        {
                            Id = 30,
                            Age = 79,
                            City = "Paris",
                            Deposit = 165,
                            Gender = 1,
                            IsNew = true
                        },
                        new
                        {
                            Id = 31,
                            Age = 26,
                            City = "Paris",
                            Deposit = 143,
                            Gender = 1,
                            IsNew = true
                        },
                        new
                        {
                            Id = 32,
                            Age = 74,
                            City = "London",
                            Deposit = 61,
                            Gender = 1,
                            IsNew = false
                        },
                        new
                        {
                            Id = 33,
                            Age = 74,
                            City = "New York",
                            Deposit = 103,
                            Gender = 0,
                            IsNew = false
                        },
                        new
                        {
                            Id = 34,
                            Age = 46,
                            City = "New York",
                            Deposit = 121,
                            Gender = 1,
                            IsNew = true
                        },
                        new
                        {
                            Id = 35,
                            Age = 47,
                            City = "New York",
                            Deposit = 214,
                            Gender = 1,
                            IsNew = false
                        },
                        new
                        {
                            Id = 36,
                            Age = 78,
                            City = "New York",
                            Deposit = 111,
                            Gender = 1,
                            IsNew = false
                        },
                        new
                        {
                            Id = 37,
                            Age = 46,
                            City = "New York",
                            Deposit = 223,
                            Gender = 1,
                            IsNew = true
                        },
                        new
                        {
                            Id = 38,
                            Age = 26,
                            City = "New York",
                            Deposit = 78,
                            Gender = 1,
                            IsNew = true
                        },
                        new
                        {
                            Id = 39,
                            Age = 49,
                            City = "Tel-Aviv",
                            Deposit = 60,
                            Gender = 1,
                            IsNew = false
                        },
                        new
                        {
                            Id = 40,
                            Age = 74,
                            City = "New York",
                            Deposit = 53,
                            Gender = 1,
                            IsNew = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
